<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>An Introduction to ‘margins’ • margins</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../jquery.sticky-kit.min.js"></script><script src="../pkgdown.js"></script><meta property="og:title" content="An Introduction to ‘margins’">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-vignette">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../index.html">margins</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/Introduction.html">An Introduction to 'margins'</a>
    </li>
    <li>
      <a href="../articles/Stata.html">Comparison with Stata's 'margins' command</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/leeper/margins">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9">
    <div class="page-header toc-ignore">
      <h1>An Introduction to ‘margins’</h1>
            
            <h4 class="date">2018-03-17</h4>
      
      <small>Source: <a href="https:/github.com/leeper/margins/blob/master/vignettes/Introduction.Rmd"><code>vignettes/Introduction.Rmd</code></a></small>

    </div>

    
    
<div class="contents">
<p><strong>margins</strong> is an effort to port Stata’s (closed source) <a href="http://www.stata.com/help.cgi?margins"><code>margins</code></a> command to R as an S3 generic method for calculating the marginal effects (or “partial effects”) of covariates included in model objects (like those of classes “lm” and “glm”). A plot method for the new “margins” class additionally ports the <code>marginsplot</code> command, and various additional functions support interpretation and visualization of such models.</p>
<p>Stata’s <code>margins</code> command is very simple and intuitive to use:</p>
<pre><code>. import delimited mtcars.csv
. quietly reg mpg c.cyl##c.hp wt
. margins, dydx(*)
------------------------------------------------------------------------------
             |            Delta-method
             |      dy/dx   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
         cyl |   .0381376   .5998897     0.06   0.950    -1.192735     1.26901
          hp |  -.0463187    .014516    -3.19   0.004     -.076103   -.0165343
          wt |  -3.119815    .661322    -4.72   0.000    -4.476736   -1.762894
------------------------------------------------------------------------------
. marginsplot</code></pre>
<div class="figure">
<img src="http://i.imgur.com/VhoaFGp.png" alt="marginsplot"><p class="caption">marginsplot</p>
</div>
<p>With <strong>margins</strong> in R, replicating Stata’s results is incredibly simple using just the <code><a href="../reference/margins.html">margins()</a></code> method to obtain average marginal effects and its <code>summary()</code> method to obtain Stata-like output:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">"margins"</span>)
x &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>cyl <span class="op">*</span><span class="st"> </span>hp <span class="op">+</span><span class="st"> </span>wt, <span class="dt">data =</span> mtcars)
(m &lt;-<span class="st"> </span><span class="kw"><a href="../reference/margins.html">margins</a></span>(x))</code></pre></div>
<pre><code>## Average marginal effects</code></pre>
<pre><code>## lm(formula = mpg ~ cyl * hp + wt, data = mtcars)</code></pre>
<pre><code>##      cyl       hp    wt
##  0.03814 -0.04632 -3.12</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(m)</code></pre></div>
<pre><code>##  factor     AME     SE       z      p   lower   upper
##     cyl  0.0381 0.5999  0.0636 0.9493 -1.1376  1.2139
##      hp -0.0463 0.0145 -3.1909 0.0014 -0.0748 -0.0179
##      wt -3.1198 0.6613 -4.7176 0.0000 -4.4160 -1.8236</code></pre>
<p>With the exception of differences in rounding, the above results match identically what Stata’s <code>margins</code> command produces. Using the <code>plot()</code> method also yields an aesthetically similar result to Stata’s <code>marginsplot</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(m)</code></pre></div>
<p><img src="Introduction_files/figure-html/marginsplot-1.png" width="672"></p>
<div id="using-optional-arguments-in-margins" class="section level2">
<h2 class="hasAnchor">
<a href="#using-optional-arguments-in-margins" class="anchor"></a>Using Optional Arguments in <code>margins</code>
</h2>
<p><strong>margins</strong> is intended as a port of (some of) the features of Stata’s <code>margins</code> command, which includes numerous options for calculating marginal effects at the mean values of a dataset (i.e., the marginal effects at the mean), an average of the marginal effects at each value of a dataset (i.e., the average marginal effect), marginal effects at representative values, and any of those operations on various subsets of a dataset. (The functionality of Stata’s command to produce <em>predictive</em> margins is not ported, as this is easily obtained from the <a href="https://cran.r-project.org/package=prediction">prediction</a> package.) In particular, Stata provides the following options:</p>
<ul>
<li>
<code>at</code>: calculate marginal effects at (potentially representative) specified values (i.e., replacing observed values with specified replacement values before calculating marginal effects)</li>
<li>
<code>atmeans</code>: calculate marginal effects at the mean (MEMs) of a dataset rather than the default behavior of calculating average marginal effects (AMEs)</li>
<li>
<code>over</code>: calculate marginal effects (including MEMs and/or AMEs at observed or specified values) on subsets of the original data (e.g., the marginal effect of a treatment separately for men and women)</li>
</ul>
<p>The <code>at</code> argument has been translated into <code><a href="../reference/margins.html">margins()</a></code> in a very similar manner. It can be used by specifying a list of variable names and specified values for those variables at which to calculate marginal effects, such as <code><a href="../reference/margins.html">margins(x, at = list(hp=150))</a></code>. When using <code>at</code>, <code><a href="../reference/margins.html">margins()</a></code> constructs modified datasets - using <code>build_datalist()</code> - containing the specified values and calculates marginal effects on each modified dataset, <code>rbind</code>-ing them back into a single “margins” object.</p>
<p>Stata’s <code>atmeans</code> argument is not implemented in <code><a href="../reference/margins.html">margins()</a></code> for various reasons, including because it is possible to achieve the effect manually through an operation like <code>data$var &lt;- mean(data$var, na.rm = TRUE)</code> and passing the modified data frame to <code><a href="../reference/margins.html">margins(x, data = data)</a></code>.</p>
<p>At present, <code><a href="../reference/margins.html">margins()</a></code> does not implement the <code>over</code> option. The reason for this is also simple: R already makes data subsetting operations quite simple using simple <code>[</code> extraction. If, for example, one wanted to calculate marginal effects on subsets of a data frame, those subsets can be passed directly to <code><a href="../reference/margins.html">margins()</a></code> via the <code>data</code> argument (as in a call to <code><a href="http://www.rdocumentation.org/packages/prediction/topics/prediction">prediction()</a></code>).</p>
<p>The rest of this vignette shows how to use <code>at</code> and <code>data</code> to obtain various kinds of marginal effects, and how to use plotting functions to visualize those inferences.</p>
<div id="average-marginal-effects-and-average-partial-effects" class="section level3">
<h3 class="hasAnchor">
<a href="#average-marginal-effects-and-average-partial-effects" class="anchor"></a>Average Marginal Effects and Average Partial Effects</h3>
<p>We can start by loading the <strong>margins</strong> package:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">"margins"</span>)</code></pre></div>
<p>We’ll use a simple example regression model based on the built-in <code>mtcars</code> dataset:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>cyl <span class="op">+</span><span class="st"> </span>hp <span class="op">*</span><span class="st"> </span>wt, <span class="dt">data =</span> mtcars)</code></pre></div>
<p>To obtain average marginal effects (AMEs), we simply call <code><a href="../reference/margins.html">margins()</a></code> on the model object created by <code>lm()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/margins.html">margins</a></span>(x)</code></pre></div>
<pre><code>## Average marginal effects</code></pre>
<pre><code>## lm(formula = mpg ~ cyl + hp * wt, data = mtcars)</code></pre>
<pre><code>##      cyl       hp     wt
##  -0.3652 -0.02527 -3.838</code></pre>
<p>The result is a data frame with special class <code>"margins"</code>. <code>"margins"</code> objects are printed in a tidy summary format, by default, as you can see above. The only difference between a <code>"margins"</code> object and a regular data frame are some additional data frame-level attributes that dictate how the object is printed.</p>
<p>The default method calculates marginal effects for all variables included in the model (ala Stata’s <code>, dydx(*)</code> option). To limit calculation to only a subset of variables, use the <code>variables</code> argument:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw"><a href="../reference/margins.html">margins</a></span>(x, <span class="dt">variables =</span> <span class="st">"hp"</span>))</code></pre></div>
<pre><code>##  factor     AME     SE       z      p   lower   upper
##      hp -0.0253 0.0105 -2.4046 0.0162 -0.0459 -0.0047</code></pre>
<p>In an ordinary least squares regression, there is really only one way of examining marginal effects (that is, on the scale of the outcome variable). In a generalized linear model (e.g., logit), however, it is possible to examine true “marginal effects” (i.e., the marginal contribution of each variable on the scale of the linear predictor) or “partial effects” (i.e., the contribution of each variable on the outcome scale, conditional on the other variables involved in the link function transformation of the linear predictor). The latter are the default in <code><a href="../reference/margins.html">margins()</a></code>, which implicitly sets the argument <code><a href="../reference/margins.html">margins(x, type = "response")</a></code> and passes that through to <code><a href="http://www.rdocumentation.org/packages/prediction/topics/prediction">prediction()</a></code> methods. To obtain the former, simply set <code><a href="../reference/margins.html">margins(x, type = "link")</a></code>. There’s some debate about which of these is preferred and even what to call the two different quantities of interest. Regardless of all of that, here’s how you obtain either:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">glm</span>(am <span class="op">~</span><span class="st"> </span>cyl <span class="op">+</span><span class="st"> </span>hp <span class="op">*</span><span class="st"> </span>wt, <span class="dt">data =</span> mtcars, <span class="dt">family =</span> binomial)</code></pre></div>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/margins.html">margins</a></span>(x, <span class="dt">type =</span> <span class="st">"response"</span>)</code></pre></div>
<pre><code>## Average marginal effects</code></pre>
<pre><code>## glm(formula = am ~ cyl + hp * wt, family = binomial, data = mtcars)</code></pre>
<pre><code>##      cyl       hp      wt
##  0.02156 0.002667 -0.5158</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/margins.html">margins</a></span>(x, <span class="dt">type =</span> <span class="st">"link"</span>) <span class="co"># the default</span></code></pre></div>
<pre><code>## Average marginal effects
## glm(formula = am ~ cyl + hp * wt, family = binomial, data = mtcars)</code></pre>
<pre><code>##     cyl      hp     wt
##  0.5156 0.05151 -12.24</code></pre>
<p>Note that some other packages available for R, as well as Stata’s <code>margins</code> and <code>mfx</code> packages enable calculation of so-called “marginal effects at means” (i.e., the marginal effect for a single observation that has covariate values equal to the means of the sample as a whole). The substantive interpretation of these is fairly ambiguous. While it was once common practice to estimate MEMs - rather than AMEs or MERs - this is now considered somewhat inappropriate because it focuses on cases that may not exist (e.g., the average of a 0/1 variable is not going to reflect a case that can actually exist in reality) and we are often interested in the effect of a variable at multiple possible values of covariates, rather than an arbitrarily selected case that is deemed “typical” in this way. As such, <code><a href="../reference/margins.html">margins()</a></code> defaults to reporting AMEs, unless modified by the <code>at</code> argument to calculate average “marginal effects for representative cases” (MERs). MEMs could be obtained by manually specifying <code>at</code> for every variable in a way that respects the variables classes and inherent meaning of the data, but that functionality is not demonstrated here.</p>
</div>
<div id="using-the-at-argument" class="section level3">
<h3 class="hasAnchor">
<a href="#using-the-at-argument" class="anchor"></a>Using the <code>at</code> Argument</h3>
<p>The <code>at</code> argument allows you to calculate marginal effects at representative cases (sometimes “MERs”) or marginal effects at means - or any other statistic - (sometimes “MEMs”), which are marginal effects for particularly interesting (sets of) observations in a dataset. This differs from marginal effects on subsets of the original data (see the next section for a demonstration of that) in that it operates on a modified set of the full dataset wherein particular variables have been replaced by specified values. This is helpful because it allows for calculation of marginal effects for <em>counterfactual</em> datasets (e.g., what if all women were instead men? what if all democracies were instead autocracies? what if all foreign cars were instead domestic?).</p>
<p>As an example, if we wanted to know if the marginal effect of horsepower (<code>hp</code>) on fuel economy differed across different types of automobile transmissions, we could simply use <code>at</code> to obtain separate marginal effect estimates for our data as if every car observation were a manual versus if every car observation were an automatic. The output of <code><a href="../reference/margins.html">margins()</a></code> is a simplified summary of the estimated marginal effects across the requested variable levels/combinations specified in <code>at</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>cyl <span class="op">+</span><span class="st"> </span>wt <span class="op">+</span><span class="st"> </span>hp <span class="op">*</span><span class="st"> </span>am, <span class="dt">data =</span> mtcars)
<span class="kw"><a href="../reference/margins.html">margins</a></span>(x, <span class="dt">at =</span> <span class="kw">list</span>(<span class="dt">am =</span> <span class="dv">0</span><span class="op">:</span><span class="dv">1</span>))</code></pre></div>
<pre><code>## Average marginal effects at specified values</code></pre>
<pre><code>## lm(formula = mpg ~ cyl + wt + hp * am, data = mtcars)</code></pre>
<pre><code>##  at(am)     cyl     wt        hp    am
##       0 -0.9339 -2.812 -0.008945 1.034
##       1 -0.9339 -2.812 -0.026392 1.034</code></pre>
<p>Because of the <code>hp * am</code> interaction in the regression, the marginal effect of horsepower differs between the two sets of results. We can also specify more than one variable to <code>at</code>, creating a potentially long list of marginal effects results. For example, we can produce marginal effects at both levels of <code>am</code> and the values from the five-number summary (minimum, Q1, median, Q3, and maximum) of observed values of <code>hp</code>. This produces 2 * 5 = 10 sets of marginal effects estimates:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/margins.html">margins</a></span>(x, <span class="dt">at =</span> <span class="kw">list</span>(<span class="dt">am =</span> <span class="dv">0</span><span class="op">:</span><span class="dv">1</span>, <span class="dt">hp =</span> <span class="kw">fivenum</span>(mtcars<span class="op">$</span>hp)))</code></pre></div>
<pre><code>## Average marginal effects at specified values</code></pre>
<pre><code>## lm(formula = mpg ~ cyl + wt + hp * am, data = mtcars)</code></pre>
<pre><code>##  at(am) at(hp)     cyl     wt        hp      am
##       0     52 -0.9339 -2.812 -0.008945  2.6864
##       1     52 -0.9339 -2.812 -0.026392  2.6864
##       0     96 -0.9339 -2.812 -0.008945  1.9188
##       1     96 -0.9339 -2.812 -0.026392  1.9188
##       0    123 -0.9339 -2.812 -0.008945  1.4477
##       1    123 -0.9339 -2.812 -0.026392  1.4477
##       0    180 -0.9339 -2.812 -0.008945  0.4533
##       1    180 -0.9339 -2.812 -0.026392  0.4533
##       0    335 -0.9339 -2.812 -0.008945 -2.2509
##       1    335 -0.9339 -2.812 -0.026392 -2.2509</code></pre>
<p>Because this is a linear model, the marginal effects of <code>cyl</code> and <code>wt</code> do not vary across levels of <code>am</code> or <code>hp</code>. The minimum and Q1 value of <code>hp</code> are also the same, so the marginal effects of <code>am</code> are the same in the first two results. As you can see, however, the marginal effect of <code>hp</code> differs when <code>am == 0</code> versus <code>am == 1</code> (first and second rows) and the marginal effect of <code>am</code> differs across levels of <code>hp</code> (e.g., between the first and third rows). As should be clear, the <code>at</code> argument is incredibly useful for getting a better grasp of the marginal effects of different covariates.</p>
<p>This becomes especially apparent when a model includes power-terms (or any other alternative functional form of a covariate). Consider, for example, the simple model of fuel economy as a function of weight, with weight included as both a first- and second-order term:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>wt <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(wt<span class="op">^</span><span class="dv">2</span>), <span class="dt">data =</span> mtcars)
<span class="kw">summary</span>(x)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt + I(wt^2), data = mtcars)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.483 -1.998 -0.773  1.462  6.238 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  49.9308     4.2113  11.856 1.21e-12 ***
## wt          -13.3803     2.5140  -5.322 1.04e-05 ***
## I(wt^2)       1.1711     0.3594   3.258  0.00286 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.651 on 29 degrees of freedom
## Multiple R-squared:  0.8191, Adjusted R-squared:  0.8066 
## F-statistic: 65.64 on 2 and 29 DF,  p-value: 1.715e-11</code></pre>
<p>Looking only at the regression results table, it is actually quite difficult to understand the effect of <code>wt</code> on fuel economy because it requires performing mental multiplication and addition on all possible values of <code>wt</code>. Using the <code>at</code> option to margins, you could quickly obtain a sense of the average marginal effect of <code>wt</code> at a range of plausible values:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/margins.html">margins</a></span>(x, <span class="dt">at =</span> <span class="kw">list</span>(<span class="dt">wt =</span> <span class="kw">fivenum</span>(mtcars<span class="op">$</span>wt)))</code></pre></div>
<pre><code>## Average marginal effects at specified values</code></pre>
<pre><code>## lm(formula = mpg ~ wt + I(wt^2), data = mtcars)</code></pre>
<pre><code>##  at(wt)      wt
##   1.513 -9.8366
##   2.542 -7.4254
##   3.325 -5.5926
##   3.650 -4.8314
##   5.424 -0.6764</code></pre>
<p>The marginal effects in the first column of results reveal that the average marginal effect of <code>wt</code> is large and negative except when <code>wt</code> is very large, in which case it has an effect not distinguishable from zero. We can easily plot these results using the <code><a href="../reference/cplot.html">cplot()</a></code> function to see the effect visually in terms of either predicted fuel economy or the marginal effect of <code>wt</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/cplot.html">cplot</a></span>(x, <span class="st">"wt"</span>, <span class="dt">what =</span> <span class="st">"prediction"</span>, <span class="dt">main =</span> <span class="st">"Predicted Fuel Economy, Given Weight"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-11-1.png" width="672"></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/cplot.html">cplot</a></span>(x, <span class="st">"wt"</span>, <span class="dt">what =</span> <span class="st">"effect"</span>, <span class="dt">main =</span> <span class="st">"Average Marginal Effect of Weight"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-11-2.png" width="672"></p>
<p>A really nice feature of Stata’s margins command is that it handles factor variables gracefully. This functionality is difficult to emulate in R, but the <code><a href="../reference/margins.html">margins()</a></code> function does its best. Here we see the marginal effects of a simple regression that includes a factor variable:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span><span class="kw">factor</span>(cyl) <span class="op">*</span><span class="st"> </span>hp <span class="op">+</span><span class="st"> </span>wt, <span class="dt">data =</span> mtcars)
<span class="kw"><a href="../reference/margins.html">margins</a></span>(x)</code></pre></div>
<pre><code>## Average marginal effects</code></pre>
<pre><code>## lm(formula = mpg ~ factor(cyl) * hp + wt, data = mtcars)</code></pre>
<pre><code>##        hp    wt  cyl6   cyl8
##  -0.04475 -3.06 1.473 0.8909</code></pre>
<p><code><a href="../reference/margins.html">margins()</a></code> recognizes the factor and displays the marginal effect for each level of the factor separately. (Caveat: this may not work with certain <code>at</code> specifications, yet.)</p>
</div>
<div id="subsetting" class="section level3">
<h3 class="hasAnchor">
<a href="#subsetting" class="anchor"></a>Subsetting</h3>
<p>Stata’s <code>margins</code> command includes an <code>over()</code> option, which allows you to very easily calculate marginal effects on subsets of the data (e.g., separately for men and women). This is useful in Stata because the program only allows one dataset in memory. Because R does not impose this restriction and further makes subsetting expressions very simple, that feature is not really useful and can be achieved using standard subsetting notation in R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span><span class="kw">factor</span>(cyl) <span class="op">*</span><span class="st"> </span>am <span class="op">+</span><span class="st"> </span>hp <span class="op">+</span><span class="st"> </span>wt, <span class="dt">data =</span> mtcars)
<span class="co"># automatic vehicles</span>
<span class="kw"><a href="../reference/margins.html">margins</a></span>(x, <span class="dt">data =</span> mtcars[mtcars<span class="op">$</span>am <span class="op">==</span><span class="st"> </span><span class="dv">0</span>, ])</code></pre></div>
<pre><code>## Average marginal effects</code></pre>
<pre><code>## lm(formula = mpg ~ factor(cyl) * am + hp + wt, data = mtcars)</code></pre>
<pre><code>##     am       hp     wt   cyl6   cyl8
##  1.706 -0.03115 -2.441 -1.715 -1.586</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># manual vehicles</span>
<span class="kw"><a href="../reference/margins.html">margins</a></span>(x, <span class="dt">data =</span> mtcars[mtcars<span class="op">$</span>am <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, ])</code></pre></div>
<pre><code>## Average marginal effects
## lm(formula = mpg ~ factor(cyl) * am + hp + wt, data = mtcars)</code></pre>
<pre><code>##     am       hp     wt   cyl6   cyl8
##  2.167 -0.03115 -2.441 -4.218 -2.656</code></pre>
<p>Because a <code>"margins"</code> object is just a data frame, it is also possible to obtain the same result by subsetting the <em>output</em> of <code><a href="../reference/margins.html">margins()</a></code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m &lt;-<span class="st"> </span><span class="kw"><a href="../reference/margins.html">margins</a></span>(x)
<span class="kw">split</span>(m, m<span class="op">$</span>am)</code></pre></div>
<pre><code>## $`0`</code></pre>
<pre><code>## Average marginal effects</code></pre>
<pre><code>## lm(formula = mpg ~ factor(cyl) * am + hp + wt, data = mtcars)</code></pre>
<pre><code>##     am       hp     wt   cyl6   cyl8
##  1.706 -0.03115 -2.441 -1.715 -1.586
## 
## $`1`</code></pre>
<pre><code>## Average marginal effects
## lm(formula = mpg ~ factor(cyl) * am + hp + wt, data = mtcars)</code></pre>
<pre><code>##     am       hp     wt   cyl6   cyl8
##  2.167 -0.03115 -2.441 -4.218 -2.656</code></pre>
<hr>
</div>
</div>
<div id="marginal-effects-plots" class="section level2">
<h2 class="hasAnchor">
<a href="#marginal-effects-plots" class="anchor"></a>Marginal Effects Plots</h2>
<p>Using <code><a href="../reference/margins.html">margins()</a></code> to calculate marginal effects enables several kinds of plotting. The built-in <code>plot()</code> method for objects of class <code>"margins"</code> creates simple diagnostic plots for examining the output of <code><a href="../reference/margins.html">margins()</a></code> in visual rather than tabular format. It is also possible to use the output of <code><a href="../reference/margins.html">margins()</a></code> to produce more typical marginal effects plots that show the marginal effect of one variable across levels of another variable. This section walks through the <code>plot()</code> method and then shows how to produce marginal effects plots using base graphics.</p>
<div id="the-plot-method-for-margins-objects" class="section level3">
<h3 class="hasAnchor">
<a href="#the-plot-method-for-margins-objects" class="anchor"></a>The <code>plot()</code> method for “margins” objects</h3>
<p>The <strong>margins</strong> package implements a <code>plot()</code> method for objects of class <code>"margins"</code> (seen above). This produces a plot similar (in spirit) to the output of Stata’s <code>marginsplot</code>. It is highly customizable, but is meant primarily as a diagnostic tool to examine the results of <code><a href="../reference/margins.html">margins()</a></code>. It simply produces, by default, a plot of marginal effects along with 95% confidence intervals for those effects. The confidence level can be modified using the <code>levels</code> argument, which is vectorized to allow multiple levels to be specified simultaneously.</p>
</div>
<div id="more-advanced-plotting" class="section level3">
<h3 class="hasAnchor">
<a href="#more-advanced-plotting" class="anchor"></a>More advanced plotting</h3>
<p>There are two common ways of visually representing the substantive results of a regression model: (1) fitted values plots, which display the fitted conditional mean outcome across levels of a covariate, and (2) marginal effects plots, which display the estimated marginal effect of a variable across levels of a covariate. This section discusses both approaches.</p>
<p>Fitted value plots can be created using <code><a href="../reference/cplot.html">cplot()</a></code> (to provide <em>conditional</em> predicted value plots or <em>conditional</em> effect plots) and both the <code>persp()</code> method and <code>image()</code> method for <code>"lm"</code> objects, which display the same type of relationships in three-dimensions (i.e., across two conditioning covariates).</p>
<p>For example, we can use <code><a href="../reference/cplot.html">cplot()</a></code> to quickly display the predicted fuel economy of a vehicle from a model:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>cyl <span class="op">+</span><span class="st"> </span>wt <span class="op">*</span><span class="st"> </span>am, <span class="dt">data =</span> mtcars)
<span class="kw"><a href="../reference/cplot.html">cplot</a></span>(x, <span class="st">"cyl"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-15-1.png" width="672"></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/cplot.html">cplot</a></span>(x, <span class="st">"wt"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-15-2.png" width="672"></p>
<p>The slopes of the predicted value lines are the marginal effect of <code>wt</code> when <code>am == 0</code> and <code>am == 1</code>. We can obtain these slopes using <code><a href="../reference/margins.html">margins()</a></code> and specifying the <code>at</code> argument:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/margins.html">margins</a></span>(x, <span class="dt">at =</span> <span class="kw">list</span>(<span class="dt">am =</span> <span class="dv">0</span><span class="op">:</span><span class="dv">1</span>))</code></pre></div>
<pre><code>## Average marginal effects at specified values</code></pre>
<pre><code>## lm(formula = mpg ~ cyl + wt * am, data = mtcars)</code></pre>
<pre><code>##  at(am)    cyl     wt     am
##       0 -1.181 -2.369 -1.566
##       1 -1.181 -6.566 -1.566</code></pre>
<p>Another plotting function - the <code>persp()</code> method for “lm” objects - gives even more functionality:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">persp</span>(x, <span class="st">"cyl"</span>, <span class="st">"wt"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-17-1.png" width="672"></p>
<p>This three-dimensional representation can be easily rotated using the <code>theta</code> and <code>phi</code> arguments. If multiple values are specified for each, facetting is automatically provided:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">persp</span>(x, <span class="st">"cyl"</span>, <span class="st">"wt"</span>, <span class="dt">theta =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">90</span>))</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-18-1.png" width="672"></p>
<p>Because these three-dimensional representations can be challenging to interpret given the distortion of displaying a three-dimensional surface in two dimensions, the <code>image()</code> method provides a “flat” alternative to convey the same information using the same semantics:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">image</span>(x, <span class="st">"cyl"</span>, <span class="st">"wt"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-19-1.png" width="672"></p>
<hr>
</div>
</div>
<div id="interpreting-interactions-with-marginal-effects" class="section level2">
<h2 class="hasAnchor">
<a href="#interpreting-interactions-with-marginal-effects" class="anchor"></a>Interpreting Interactions with Marginal Effects</h2>
<p>One of principal motives for developing <strong>margins</strong> is to facilitate the substantive interpretation of interaction terms in regression models. A large literature now describes the difficulties of such interpretations in both linear and non-linear regression models. This vignette walks through some of that interpretation.</p>
<div id="interactions-in-ols" class="section level3">
<h3 class="hasAnchor">
<a href="#interactions-in-ols" class="anchor"></a>Interactions in OLS</h3>
<p>If we begin with a simple example of a regression model with an interaction term, the difficulties of interpretation become almost immediately clear. In this first model, we’ll use the <code>mtcars</code> dataset to understand vehicle fuel economy as a function of <code>drat</code> (rear axle ratio), <code>wt</code> (weight), and their interaction. As Brambor et al. (2006) make clear, the most common mistake in such models is estimating the model without the constituent variables. We can see why this is a problem by estimating the model with and without the constituent terms:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>drat<span class="op">:</span>wt, <span class="dt">data =</span> mtcars))</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ drat:wt, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.3319 -2.3669 -0.6585  2.0952  8.2124 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  40.6488     3.1335  12.972 7.77e-14 ***
## drat:wt      -1.8339     0.2728  -6.723 1.89e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.87 on 30 degrees of freedom
## Multiple R-squared:  0.6011, Adjusted R-squared:  0.5878 
## F-statistic:  45.2 on 1 and 30 DF,  p-value: 1.886e-07</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>drat <span class="op">*</span><span class="st"> </span>wt, <span class="dt">data =</span> mtcars))</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ drat * wt, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.8913 -1.8634 -0.3398  1.3247  6.4730 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)    5.550     12.631   0.439   0.6637  
## drat           8.494      3.321   2.557   0.0162 *
## wt             3.884      3.798   1.023   0.3153  
## drat:wt       -2.543      1.093  -2.327   0.0274 *
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.839 on 28 degrees of freedom
## Multiple R-squared:  0.7996, Adjusted R-squared:  0.7782 
## F-statistic: 37.25 on 3 and 28 DF,  p-value: 6.567e-10</code></pre>
<p>Clearly the models produce radically different estimates and goodness-of-fit to the original data. As a result, it’s important to use all constituent terms in the model even if they are thought <em>a priori</em> to have coefficients of zero. Now let’s see how we can use <code><a href="../reference/margins.html">margins()</a></code> to interpret a more complex three-way interaction:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x1 &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>drat <span class="op">*</span><span class="st"> </span>wt <span class="op">*</span><span class="st"> </span>am, <span class="dt">data =</span> mtcars)
<span class="kw">summary</span>(<span class="kw"><a href="../reference/margins.html">margins</a></span>(x1))</code></pre></div>
<pre><code>##  factor     AME     SE       z      p   lower   upper
##      am -2.4729 3.0342 -0.8150 0.4151 -8.4198  3.4739
##    drat  0.8882 1.7047  0.5210 0.6023 -2.4529  4.2293
##      wt -5.8203 0.8769 -6.6373 0.0000 -7.5390 -4.1016</code></pre>
<p>By default, <code><a href="../reference/margins.html">margins()</a></code> will supply the average marginal effects of the constituent variables in the model. Note how the <code>drat:wt</code> term is not expressed in the margins results. This is because the contribution of the <code>drat:wt</code> term is incorporated into the marginal effects for the constituent variables. Because there is a significant interaction, we can see this by examining margins at different levels of the constituent variables. The <code>drat</code> variable is continuous, taking values from 2.76 to 4.93:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/margins.html">margins</a></span>(x1, <span class="dt">at =</span> <span class="kw">list</span>(<span class="dt">drat =</span> <span class="kw">range</span>(mtcars<span class="op">$</span>drat)))</code></pre></div>
<pre><code>## Average marginal effects at specified values</code></pre>
<pre><code>## lm(formula = mpg ~ drat * wt * am, data = mtcars)</code></pre>
<pre><code>##  at(drat)   drat     wt       am
##      2.76 0.8882 -4.989 -0.04699
##      4.93 0.8882 -7.271 -6.09246</code></pre>
<p>Now <code><a href="../reference/margins.html">margins()</a></code> returns two <code>"margins"</code> objects, one for each combination of values specified in <code>drat</code>. We can see in the above that cars with a low axle ratio (<code>drat == 2.76</code>), the average marginal effect of weight is a reduction in fuel economy of 4.99 miles per gallon. For vehicles with a higher ratio (<code>drat == 4.93</code>), this reduction in fuel economy is lower at 7.27 miles per gallon. Yet this is also not fully accurate because it mixes the automatic and manual cars, so we may want to further break out the results by transmission type.</p>
<p>The <code>at</code> argument accepts multiple named combinations of variables, so we can specify particular values of both <code>drat</code> and <code>wt</code> and <code>am</code> for which we would like to understand the marginal effect of each variable. For example, we might want to look at the effects of each variable for vehicles with varying axle ratios but also across some representative values of the <code>wt</code> distribution, separately for manual and automatic vehicles. (Note that the order of values in the <code>at</code> object does matter and it can inclue variables that are not explicitly being modelled).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">wts &lt;-<span class="st"> </span>prediction<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/prediction/topics/seq_range">seq_range</a></span>(mtcars<span class="op">$</span>wt, <span class="dv">10</span>)
m1 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/margins.html">margins</a></span>(x1, <span class="dt">at =</span> <span class="kw">list</span>(<span class="dt">wt =</span> wts, <span class="dt">drat =</span> <span class="kw">range</span>(mtcars<span class="op">$</span>drat), <span class="dt">am =</span> <span class="dv">0</span><span class="op">:</span><span class="dv">1</span>))
<span class="kw">nrow</span>(m1)<span class="op">/</span><span class="kw">nrow</span>(mtcars)</code></pre></div>
<pre><code>## [1] 40</code></pre>
<p>As you can see above, the result is a relatively long data frame (basically a stack of <code>"margins"</code> objects specific to each of the - 40 - requested combinations of <code>at</code> values). We can examine the whole stack using <code>summary()</code>, but it’s an extremely long output (one row for each estimate times the number of unique combinations of <code>at</code> values, so 120 rows in this instance).</p>
<p>An easier way to understand all of this is to use graphing. The <code><a href="../reference/cplot.html">cplot()</a></code> function, in particular, is useful here. We can, for example, plot the marginal effect of axle ratio across levels of vehicle weight, separately for automatic vehicles (in red) and manual vehicles (in blue):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/cplot.html">cplot</a></span>(x1, <span class="dt">x =</span> <span class="st">"wt"</span>, <span class="dt">dx =</span> <span class="st">"drat"</span>, <span class="dt">what =</span> <span class="st">"effect"</span>, 
      <span class="dt">data =</span> mtcars[mtcars[[<span class="st">"am"</span>]] <span class="op">==</span><span class="st"> </span><span class="dv">0</span>,], 
      <span class="dt">col =</span> <span class="st">"red"</span>, <span class="dt">se.type =</span> <span class="st">"shade"</span>,
      <span class="dt">xlim =</span> <span class="kw">range</span>(mtcars[[<span class="st">"wt"</span>]]), <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">20</span>, <span class="dv">20</span>), 
      <span class="dt">main =</span> <span class="st">"AME of Axle Ratio on Fuel Economy"</span>)
<span class="kw"><a href="../reference/cplot.html">cplot</a></span>(x1, <span class="dt">x =</span> <span class="st">"wt"</span>, <span class="dt">dx =</span> <span class="st">"drat"</span>, <span class="dt">what =</span> <span class="st">"effect"</span>, 
      <span class="dt">data =</span> mtcars[mtcars[[<span class="st">"am"</span>]] <span class="op">==</span><span class="st"> </span><span class="dv">1</span>,], 
      <span class="dt">col =</span> <span class="st">"blue"</span>, <span class="dt">se.type =</span> <span class="st">"shade"</span>, 
      <span class="dt">draw =</span> <span class="st">"add"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-24-1.png" width="768"></p>
<p><code><a href="../reference/cplot.html">cplot()</a></code> only provides AME displays over the observed range of the data (noted by the rug), so we can see that it would be inappropriate to compare the average marginal effect of axle ratio for the two transmission types at extreme values of weight.</p>
<p>Another use of these types of plots can be to interpret power terms, to see the average marginal effect of a variable across values of itself. Consider the following, for example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x1b &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>am <span class="op">*</span><span class="st"> </span>wt <span class="op">+</span><span class="st"> </span>am <span class="op">*</span><span class="st"> </span><span class="kw">I</span>(wt<span class="op">^</span><span class="dv">2</span>), <span class="dt">data =</span> mtcars)
<span class="kw"><a href="../reference/cplot.html">cplot</a></span>(x1b, <span class="dt">x =</span> <span class="st">"wt"</span>, <span class="dt">dx =</span> <span class="st">"wt"</span>, <span class="dt">what =</span> <span class="st">"effect"</span>, 
      <span class="dt">data =</span> mtcars[mtcars[[<span class="st">"am"</span>]] <span class="op">==</span><span class="st"> </span><span class="dv">0</span>,], 
      <span class="dt">col =</span> <span class="st">"red"</span>, <span class="dt">se.type =</span> <span class="st">"shade"</span>,
      <span class="dt">xlim =</span> <span class="kw">range</span>(mtcars[[<span class="st">"wt"</span>]]), <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">20</span>, <span class="dv">20</span>), 
      <span class="dt">main =</span> <span class="st">"AME of Weight on Fuel Economy"</span>)
<span class="kw"><a href="../reference/cplot.html">cplot</a></span>(x1b, <span class="dt">x =</span> <span class="st">"wt"</span>, <span class="dt">dx =</span> <span class="st">"wt"</span>, <span class="dt">what =</span> <span class="st">"effect"</span>, 
      <span class="dt">data =</span> mtcars[mtcars[[<span class="st">"am"</span>]] <span class="op">==</span><span class="st"> </span><span class="dv">1</span>,], 
      <span class="dt">col =</span> <span class="st">"blue"</span>, <span class="dt">se.type =</span> <span class="st">"shade"</span>, 
      <span class="dt">draw =</span> <span class="st">"add"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-25-1.png" width="768"></p>
<p>Note, however, that interpreting these kind of continuous-by-continuous interaction terms is slightly more complex because the marginal effect of both constituent variables always depends on the level of the other variable. We’ll use the horsepower (<code>hp</code>) variable from <code>mtcars</code> to understand this type of interaction. We can start by looking at the AMEs:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x2 &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>hp <span class="op">*</span><span class="st"> </span>wt, <span class="dt">data =</span> mtcars)
<span class="kw"><a href="../reference/margins.html">margins</a></span>(x2)</code></pre></div>
<pre><code>## Average marginal effects</code></pre>
<pre><code>## lm(formula = mpg ~ hp * wt, data = mtcars)</code></pre>
<pre><code>##        hp     wt
##  -0.03051 -4.132</code></pre>
<p>On average across the cases in the dataset, the effect of horsepower is slightly negative. On average, the effect of weight is also negative. Both decrease fuel economy. But what is the marginal effect of each variable across the range of values we actually observe in the data. To get a handle on this, we can use the <code>persp()</code> method provided by margins.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">persp</span>(x2, <span class="st">"wt"</span>, <span class="st">"hp"</span>, <span class="dt">theta =</span> <span class="kw">c</span>(<span class="dv">45</span>, <span class="dv">135</span>, <span class="dv">225</span>, <span class="dv">315</span>), <span class="dt">what =</span> <span class="st">"effect"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-27-1.png" width="672"></p>
<p>To make sense of this set of plots (actually, the same plot seen from four different angles), it will also be helpful to have the original regression results close at-hand:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(x2)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ hp * wt, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.0632 -1.6491 -0.7362  1.4211  4.5513 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 49.80842    3.60516  13.816 5.01e-14 ***
## hp          -0.12010    0.02470  -4.863 4.04e-05 ***
## wt          -8.21662    1.26971  -6.471 5.20e-07 ***
## hp:wt        0.02785    0.00742   3.753 0.000811 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.153 on 28 degrees of freedom
## Multiple R-squared:  0.8848, Adjusted R-squared:  0.8724 
## F-statistic: 71.66 on 3 and 28 DF,  p-value: 2.981e-13</code></pre>
<p>If we express the regression results as an equation: <code>mpg = 49.81 + (-0.12 * hp) + (-8.22 * wt) + (0.03 * hp*wt)</code>, it will be easy to see how the three-dimensional surface above reflects various partial derivatives of the regression equation.</p>
<p>For example, if we take the partial derivative of the regression equation with respect to <code>wt</code> (i.e., the marginal effect of weight), the equation is: <code>d_mpg/d_wt = (-8.22) + (0.03 * hp)</code>. This means that the marginal effect of weight is large and negative when horsepower is zero (which never occurs in the <code>mtcars</code> dataset) and decreases in magnitude and becoming more positive as horsepower increases. We can see this in the above graph that the marginal effect of weight is constant across levels of <code>weight</code> because <code>wt</code> does not enter into the partial derivative. Across levels, of horsepower, however, the marginal effect becomes more positive. This is clear looking at the “front” or “back” edges of the surface, which are straight-linear increases. The slope of those edges is 0.03 (the coefficient on the interaction term).</p>
<p>If we then take the partial derivative with respect to <code>hp</code> (to obtain the marginal effect of horsepower), the equation is: <code>d_mpg/d_hp = (-0.12) + (0.03 * wt)</code>. When <code>wt</code> is zero, this partial derivative (or marginal effect) is -0.12 miles/gallon. The observed range of <code>wt</code>, however, is only: 1.513, 5.424. We can see these results in the analogous graph of the marginal effects of horsepower (below). The “front” and “back” edges of the graph are now flat (reflecting how the marginal effect of horsepower is constant across levels of horsepower), while the “front-left” and “right-back” edges of the surface are lines with slope 0.03, reflecting the coefficient on the interaction term.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">persp</span>(x2, <span class="st">"hp"</span>, <span class="st">"wt"</span>, <span class="dt">theta =</span> <span class="kw">c</span>(<span class="dv">45</span>, <span class="dv">135</span>, <span class="dv">225</span>, <span class="dv">315</span>), <span class="dt">what =</span> <span class="st">"effect"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-29-1.png" width="672"></p>
<p>An alternative way of plotting these results is to take “slices” of the three-dimensional surface and present them in a two-dimensional graph, similar to what we did above with the indicator-by-continuous approach. That strategy would be especially appropriate for a categorical-by-continuous interaction where the categories of the first variable did not necessarily have a logical ordering sufficient to draw a three-dimensional surface.</p>
</div>
<div id="ggplot2-examples" class="section level3">
<h3 class="hasAnchor">
<a href="#ggplot2-examples" class="anchor"></a>ggplot2 examples</h3>
<p>It should be noted that <code><a href="../reference/cplot.html">cplot()</a></code> returns a fairly tidy data frmae, making it possible to use ggplot2 as an alternative plotting package to display the kinds of relationships of typical interest. For example, returning to our earlier example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x1 &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>drat <span class="op">*</span><span class="st"> </span>wt <span class="op">*</span><span class="st"> </span>am, <span class="dt">data =</span> mtcars)
cdat &lt;-<span class="st"> </span><span class="kw"><a href="../reference/cplot.html">cplot</a></span>(x1, <span class="st">"wt"</span>, <span class="dt">draw =</span> <span class="ot">FALSE</span>)
<span class="kw">head</span>(cdat)</code></pre></div>
<pre><code>##      xvals    yvals    upper    lower
## 1 1.513000 28.66765 33.04903 24.28627
## 2 1.675958 27.71126 31.71243 23.71010
## 3 1.838917 26.75488 30.38319 23.12656
## 4 2.001875 25.79849 29.06385 22.53313
## 5 2.164833 24.84210 27.75810 21.92610
## 6 2.327792 23.88571 26.47147 21.29996</code></pre>
<p>From this structure, it is very easy to draw a predicted values plot</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">"ggplot2"</span>)
<span class="kw">ggplot</span>(cdat, <span class="kw">aes</span>(<span class="dt">x =</span> xvals)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> yvals)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> upper), <span class="dt">linetype =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> lower), <span class="dt">linetype =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">"Predicted Fuel Economy (mpg) by Weight"</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">"Weight (1000 lbs)"</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">"Predicted Value"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-31-1.png" width="768"></p>
<p>And the same thing is possible with a marginal effect calculation:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cdat &lt;-<span class="st"> </span><span class="kw"><a href="../reference/cplot.html">cplot</a></span>(x1, <span class="st">"wt"</span>, <span class="st">"drat"</span>, <span class="dt">what =</span> <span class="st">"effect"</span>, <span class="dt">draw =</span> <span class="ot">FALSE</span>)
<span class="kw">ggplot</span>(cdat, <span class="kw">aes</span>(<span class="dt">x =</span> xvals)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> yvals)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> upper), <span class="dt">linetype =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> lower), <span class="dt">linetype =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">"AME of Axle Ratio on Fuel Economy (mpg) by Weight"</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">"Weight (1000 lbs)"</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">"AME of Axle Ratio"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-32-1.png" width="768"></p>
</div>
<div id="interactions-in-logit" class="section level3">
<h3 class="hasAnchor">
<a href="#interactions-in-logit" class="anchor"></a>Interactions in Logit</h3>
<p>Interaction terms in generalized linear models have been even more controversial than interaction terms in linear regression (Norton et al. 2004). The result is a realization over the past decade that almost all extant interpretations of GLMs with interaction terms (or hypothesizing moderating effects) have been misinterpreted. Stata’s <code>margins</code> command and the debate that preceded it have led to a substantial change in analytic practices.</p>
<p>For this, we’ll use the <code>Pima.te</code> dataset from <strong>MASS</strong>, which should be preinstalled in R, but we’ll manually load it just in case:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">utils<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/utils/topics/data">data</a></span>(Pima.te, <span class="dt">package =</span> <span class="st">"MASS"</span>)
<span class="kw">head</span>(Pima.te)</code></pre></div>
<pre><code>##   npreg glu bp skin  bmi   ped age type
## 1     6 148 72   35 33.6 0.627  50  Yes
## 2     1  85 66   29 26.6 0.351  31   No
## 3     1  89 66   23 28.1 0.167  21   No
## 4     3  78 50   32 31.0 0.248  26  Yes
## 5     2 197 70   45 30.5 0.158  53  Yes
## 6     5 166 72   19 25.8 0.587  51  Yes</code></pre>
<p>This dataset contains data on 332 women, including whether or not they are diabetic (<code>type</code>). We’ll examine a simple model with an interaction term between age and a skin thickness measure to explain diabetes status in these women:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(g1 &lt;-<span class="st"> </span><span class="kw">glm</span>(type <span class="op">~</span><span class="st"> </span>age <span class="op">*</span><span class="st"> </span>skin, <span class="dt">data =</span> Pima.te, <span class="dt">family =</span> binomial))</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = type ~ age * skin, family = binomial, data = Pima.te)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.9474  -0.8654  -0.5208   1.1261   2.1079  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -7.880929   1.469932  -5.361 8.26e-08 ***
## age          0.164912   0.042398   3.890  0.00010 ***
## skin         0.177608   0.044946   3.952 7.77e-05 ***
## age:skin    -0.003628   0.001316  -2.756  0.00585 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 420.3  on 331  degrees of freedom
## Residual deviance: 364.1  on 328  degrees of freedom
## AIC: 372.1
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Logit models (like all GLMs) present the dual challenges of having coefficients that are directly uninterpretable and marginal effects that depend on the values of the data. As a result, we can see coefficients and statistical significance tests above but it’s hard to make sense of those results without converting them into a more intuitive quantity, such as the predicted probability of having diabetes. We can see that increasing age and increasing skin thickness are associated with higher rates of diabetes, but the negative coefficient on the interaction term makes it hard to express the substantive size of these relationships. We can use <code>margins</code> to achieve this. By default, however, <code><a href="../reference/margins.html">margins()</a></code> reports results on the response scale (thus differing from the default behavior of <code><a href="http://www.rdocumentation.org/packages/stats/topics/predict">stats::predict()</a></code>):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/margins.html">margins</a></span>(g1)</code></pre></div>
<pre><code>## Average marginal effects</code></pre>
<pre><code>## glm(formula = type ~ age * skin, family = binomial, data = Pima.te)</code></pre>
<pre><code>##       age    skin
##  0.009283 0.01064</code></pre>
<p>These marginal effects reflect, on average across all of the cases in our data, how much more likely a woman is to have diabetes. Because this is an <em>instantaneous</em> effect, it can be a little hard to conceptualize. I find it helpful to take a look at a predicted probability plot to understand what is going on. Let’s take a look, for example, at the effect of age on the probability of having diabetes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/cplot.html">cplot</a></span>(g1, <span class="st">"age"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-36-1.png" width="672"></p>
<p>The above graph shows that as age increase, the probability of having diabetes increases. When a woman is 20 years old, the probability is about .20 whereas when a woman is 80, the probability is about 0.80. In essence, the marginal effect of <code>age</code> reported above is the slope of this predicted probability plot at the mean age of women in the dataset (which is 31.3162651). Clearly, this quantity is useful (it’s the impact of age for the average-aged woman) but the logit curve shows that the marginal effect of <code>age</code> differs considerably across ages and, as we know from above with linear models, also depends on the other variable in the interaction (skin thickness). To really understand what is going on, we need to graph the data. Let’s look at the perspective plot like the one we drew for the OLS model, above:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">persp</span>(g1, <span class="dt">theta =</span> <span class="kw">c</span>(<span class="dv">45</span>, <span class="dv">135</span>, <span class="dv">225</span>, <span class="dv">315</span>), <span class="dt">what =</span> <span class="st">"prediction"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-37-1.png" width="672"></p>
<p>This graph is much more complicated than the analogous graph for an OLS model, this is because of the conversion between the log-odds scale of the linear predictors and the distribution of the data. What we can see is that the average marginal effect of age (across all of the women in our dataset) is highest when a woman is middle age and skin thickness is low. In these conditions, the marginal change in the probability of diabetes is about 3%, but the AME of age is nearly zero at higher and lower ages. Indeed, as skin thickness increases, the marginal effect of age flattens out and actually becomes negative (such that increasing age actually decreases the probability of diabetes for women with thick arms).</p>
<p>Now let’s examine the average marginal effects of skin thickness across levels of age and skin thickness:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">persp</span>(g1, <span class="dt">theta =</span> <span class="kw">c</span>(<span class="dv">45</span>, <span class="dv">135</span>, <span class="dv">225</span>, <span class="dv">315</span>), <span class="dt">what =</span> <span class="st">"effect"</span>)</code></pre></div>
<p><img src="Introduction_files/figure-html/unnamed-chunk-38-1.png" width="672"></p>
<p>This graphs is somewhat flatter, indicating that the average marginal effects of skin thickness vary less than those for age. Yet, the AME of skin thickness is as high as 2% when age is low and skin thickness is high. Interestingly, however, this effect actually becomes negative as age increases. The marginal effect of skin thickness is radically different for young and old women.</p>
<p>For either of these cases, it would also be appropriate to draw two-dimensional plots of “slides” of these surfaces and incorporate measures of uncertainty. It is extremely difficult to convey standard errors or confidence intervals in a three-dimensional plot, so those could be quite valuable.</p>
<p>It is also worth comparing the above graphs to those that would result from a model without the interaction term between <code>age</code> and <code>skin</code>. It looks quite different (note, however, that it is also drawn from a higher perspective to better see the shape of the surface):</p>
<p><img src="Introduction_files/figure-html/unnamed-chunk-39-1.png" width="768"><img src="Introduction_files/figure-html/unnamed-chunk-39-2.png" width="768"></p>
<p>Our inferences about the impact of a variable on the outcome in a GLM therefore depend quite heavily on how the interaction is modelled. It also worth pointing out that the surface of the AMEs on the log-odds (linear) scale are actually flat (as in an OLS model), so the the curved shape of the plot immediately above reflects only the conversion of the effects from the linear scale to the probability scale (and the distributions of the covariates), whereas the much more unusual surface from earlier reflects that conversion and the interaction between the two variables (and the distributions thereof). If we were to plot the interaction model on the scale of the log-odds, it would look much more like the plot from the OLS models (this is left as an exercise to the reader).</p>
<hr>
</div>
</div>
<div id="references" class="section level2">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<p>Bartus, Tamas. 2005. “Estimation of marginal effects using margeff.” <em>Stata Journal</em> 5: 309-329.</p>
<p>Brambor, Thomas, William Clark &amp; Matt Golder. 2006. “Understanding Interaction Models: Improving Empirical Analyses.” <em>Political Analysis</em> 14: 63-82.</p>
<p>Greene, William H. 2012. <em>Econometric Analysis.</em> 7th ed. Upper Saddle River, NJ: Prentice Hall.</p>
<p>Long, J. Scott. 1997. <em>Regression Models for Categorical and Limited Dependent Variables.</em> Sage Publications: Thousand Oaks, CA.</p>
<p>Norton, Edward C., Hua Wang, and Chunrong Ai. 2004. “Computing interaction effects and standard errors in logit and probit models.” <em>The Stata Journal</em> 4(2): 154-167.</p>
<p>Stata Corporation. “margins”. Software Documentation. Available from: <a href="http://www.stata.com/manuals13/rmargins.pdf" class="uri">http://www.stata.com/manuals13/rmargins.pdf</a>.</p>
<p>Williams, Richard. 2012. “Using the margins command to estimate and interpret adjusted predictions and marginal effects.” <em>Stata Journal</em> 12: 308-331.</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#using-optional-arguments-in-margins">Using Optional Arguments in <code>margins</code></a></li>
      <li><a href="#marginal-effects-plots">Marginal Effects Plots</a></li>
      <li><a href="#interpreting-interactions-with-marginal-effects">Interpreting Interactions with Marginal Effects</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Thomas J. Leeper.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  </body>
</html>
