#' @title Plot Marginal Effects Estimates
#' @description An implementation of Stata's \samp{marginsplot} as an S3
#'   generic function
#' @param x An object of class \dQuote{margins}, as returned by
#'   \code{\link{margins}}.
#' @param level A numeric value between 0 and 1 indicating the confidence level
#'   to use when drawing error bars.
#' @param term_map named character vector. Names refer to the original
#'   term/variable names. Values refer to the term names that will appear in
#'   the plot. Terms which are omitted from this vector will be omitted from the
#'   plot.
#' @param \dots Additional arguments passed to
#'   \code{\link[ggplot2]{geom_pointrange}}, such as \code{shape}, \code{size},
#'   \code{colour}, etc.
#' @details This function is invoked for its side effect: a basic dot plot with
#' error bars displaying marginal effects as generated by
#' \code{\link{margins}}, in the style of Stata's \samp{marginsplot} command.
#' @return The original \dQuote{margins} object \code{x}, invisibly.
#' @examples
#' \dontrun{
#'   require("datasets")
#'   x <- lm(mpg ~ cyl * hp + wt, data = mtcars)
#'   mar <- margins(x)
#'   plot(mar)
#' }
#' 
#' @seealso \code{\link{margins}}, \code{\link{persp.lm}}
#' @keywords graphics
#' @importFrom graphics abline axis plot points segments
#' @export
plot.margins <- 
function(x, 
         level = 0.95,
         term_map = NULL,
         ...) {
    
    # extract summary
    summ <- summary(x, level = level, by_factor = TRUE)

    # subset and rename
    if (is.null(term_map)) {
        summ$factor <- paste0('dydx_', summ$factor)
    } else {
        # TODO: sanity checks
        summ <- summ[summ$factor %in% names(term_map),]
        summ$factor <- term_map[match(summ$factor, names(term_map))]
    }

    # main plot command
    p <- ggplot(summ, aes(x = factor, y = AME, ymin = lower, ymax = upper)) +
         geom_pointrange(...) +
         theme_minimal() +
         ylab("Average Marginal Effect") +
         xlab("")

    # output
    return(p) 
}
